version: '2'
services:
  test-service:
    image: consul_test:v2
    restart: always
    build:
      context: ../src
      dockerfile: ../Docker/Dockerfile_ConsulTestapp
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
  consul:
    image: consul:1.9.1
    hostname: consul
    container_name: consul
    restart: always
    ports:
      - "8300:8300"
      - "8301:8301"
      - "8301:8301/udp"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    environment:
      - enable-local-script-checks=true
    command: ["consul", "agent", "-server", "-ui", "-bind", "0.0.0.0", "-client", "0.0.0.0", "-data-dir", "/consul/data", "-config-dir", "/consul/config", "-bootstrap", "-datacenter", "docker"]
    volumes:
      - consul-node1_data:/bitnami
volumes:
  consul-node1_data:
    driver: local